import 'package:supabase_flutter/supabase_flutter.dart';

import '../models/admin_action_log.dart';
import '../models/application.dart';
import '../models/employer_profile.dart';
import '../models/job_listing.dart';
import '../models/job_seeker_profile.dart';
import '../repositories/admin_repository.dart';

class SupabaseAdminRepository implements AdminRepository {
  const SupabaseAdminRepository(this._client, this._adminUserId);

  final SupabaseClient _client;
  final String _adminUserId;

  /// Placeholder id for [AdminActionLog] instances that will be persisted via
  /// [logAdminAction].  The real id is generated by the database
  /// (`gen_random_uuid()` default) — [logAdminAction] strips this field before
  /// inserting, so the value here is never written to the database.
  static const _pendingId = '';

  // ── Action Logging ────────────────────────────────────────────────────────

  @override
  Future<void> logAdminAction(AdminActionLog log) async {
    // Omit 'id' so the database generates it via gen_random_uuid() default.
    final payload = Map<String, dynamic>.from(log.toJson())..remove('id');
    await _client.from('admin_action_logs').insert(payload);
  }

  @override
  Future<List<AdminActionLog>> getAdminActionLogs({
    DateTime? startDate,
    DateTime? endDate,
    String? actionType,
    String? resourceType,
  }) async {
    var query = _client.from('admin_action_logs').select();

    if (startDate != null) {
      query = query.gte('timestamp', startDate.toIso8601String());
    }
    if (endDate != null) {
      query = query.lte('timestamp', endDate.toIso8601String());
    }
    if (actionType != null && actionType.isNotEmpty) {
      query = query.eq('action_type', actionType);
    }
    if (resourceType != null && resourceType.isNotEmpty) {
      query = query.eq('resource_type', resourceType);
    }

    final rows = await query.order('timestamp', ascending: false);
    return rows
        .map((r) => AdminActionLog.fromJson(Map<String, dynamic>.from(r)))
        .toList();
  }

  // ── Read Data ─────────────────────────────────────────────────────────────

  @override
  Future<JobSeekerProfile?> getJobSeekerProfile(String userId) async {
    final row = await _client
        .from('job_seeker_profiles')
        .select()
        .eq('user_id', userId)
        .maybeSingle();
    if (row == null) {
      return null;
    }
    return JobSeekerProfile.fromJson(_fromJobSeekerRow(row));
  }

  @override
  Future<EmployerProfile?> getEmployerProfile(String employerId) async {
    final row = await _client
        .from('employer_profiles')
        .select()
        .eq('id', employerId)
        .maybeSingle();
    if (row == null) {
      return null;
    }
    return EmployerProfile.fromJson(_fromEmployerRow(row));
  }

  @override
  Future<List<Application>> getApplicationsForJob(String jobId) async {
    final rows = await _client
        .from('job_applications')
        .select()
        .eq('job_listing_id', jobId)
        .order('updated_at', ascending: false);
    return rows
        .map((r) => _fromApplicationRow(Map<String, dynamic>.from(r)))
        .toList();
  }

  @override
  Future<List<JobListing>> getAllJobListings() async {
    final rows = await _client
        .from('job_listings')
        .select()
        .order('created_at', ascending: false);
    return rows.map((r) => JobListing.fromJson(_fromJobListingRow(r))).toList();
  }

  @override
  Future<List<Application>> getAllApplications() async {
    final rows = await _client
        .from('job_applications')
        .select()
        .order('updated_at', ascending: false);
    return rows
        .map((r) => _fromApplicationRow(Map<String, dynamic>.from(r)))
        .toList();
  }

  // ── Edit Data ─────────────────────────────────────────────────────────────

  @override
  Future<void> updateJobListing(
    String jobId,
    JobListing updated,
    String reason,
  ) async {
    final beforeRow = await _client
        .from('job_listings')
        .select()
        .eq('id', jobId)
        .maybeSingle();

    await _client.from('job_listings').update(updated.toJson()).eq('id', jobId);

    await logAdminAction(
      AdminActionLog(
        id: _pendingId,
        adminUserId: _adminUserId,
        actionType: AdminActionLog.actionUpdate,
        resourceType: AdminActionLog.resourceJobListing,
        resourceId: jobId,
        changesBefore: beforeRow != null
            ? Map<String, dynamic>.from(beforeRow)
            : null,
        changesAfter: updated.toJson(),
        reason: reason,
        timestamp: DateTime.now(),
      ),
    );
  }

  @override
  Future<void> updateApplication(
    String appId,
    Application updated,
    String reason,
  ) async {
    final beforeRow = await _client
        .from('job_applications')
        .select()
        .eq('id', appId)
        .maybeSingle();

    await _client
        .from('job_applications')
        .update(updated.toJson())
        .eq('id', appId);

    await logAdminAction(
      AdminActionLog(
        id: _pendingId,
        adminUserId: _adminUserId,
        actionType: AdminActionLog.actionUpdate,
        resourceType: AdminActionLog.resourceApplication,
        resourceId: appId,
        changesBefore: beforeRow != null
            ? Map<String, dynamic>.from(beforeRow)
            : null,
        changesAfter: updated.toJson(),
        reason: reason,
        timestamp: DateTime.now(),
      ),
    );
  }

  @override
  Future<void> updateJobSeekerProfile(
    String userId,
    JobSeekerProfile updated,
    String reason,
  ) async {
    final beforeRow = await _client
        .from('job_seeker_profiles')
        .select()
        .eq('user_id', userId)
        .maybeSingle();

    await _client
        .from('job_seeker_profiles')
        .update(updated.toJson())
        .eq('user_id', userId);

    await logAdminAction(
      AdminActionLog(
        id: _pendingId,
        adminUserId: _adminUserId,
        actionType: AdminActionLog.actionUpdate,
        resourceType: AdminActionLog.resourceJobSeekerProfile,
        resourceId: userId,
        changesBefore: beforeRow != null
            ? Map<String, dynamic>.from(beforeRow)
            : null,
        changesAfter: updated.toJson(),
        reason: reason,
        timestamp: DateTime.now(),
      ),
    );
  }

  @override
  Future<void> updateEmployerProfile(
    String empId,
    EmployerProfile updated,
    String reason,
  ) async {
    final beforeRow = await _client
        .from('employer_profiles')
        .select()
        .eq('id', empId)
        .maybeSingle();

    await _client
        .from('employer_profiles')
        .update(updated.toJson())
        .eq('id', empId);

    await logAdminAction(
      AdminActionLog(
        id: _pendingId,
        adminUserId: _adminUserId,
        actionType: AdminActionLog.actionUpdate,
        resourceType: AdminActionLog.resourceEmployerProfile,
        resourceId: empId,
        changesBefore: beforeRow != null
            ? Map<String, dynamic>.from(beforeRow)
            : null,
        changesAfter: updated.toJson(),
        reason: reason,
        timestamp: DateTime.now(),
      ),
    );
  }

  // ── Delete ────────────────────────────────────────────────────────────────

  @override
  Future<void> deleteApplication(String appId, String reason) async {
    final beforeRow = await _client
        .from('job_applications')
        .select()
        .eq('id', appId)
        .maybeSingle();

    // Soft delete: mark archived
    await _client
        .from('job_applications')
        .update({'is_archived': true})
        .eq('id', appId);

    await logAdminAction(
      AdminActionLog(
        id: _pendingId,
        adminUserId: _adminUserId,
        actionType: AdminActionLog.actionDelete,
        resourceType: AdminActionLog.resourceApplication,
        resourceId: appId,
        changesBefore: beforeRow != null
            ? Map<String, dynamic>.from(beforeRow)
            : null,
        reason: reason,
        timestamp: DateTime.now(),
      ),
    );
  }

  @override
  Future<void> deleteJobListing(String jobId, String reason) async {
    final beforeRow = await _client
        .from('job_listings')
        .select()
        .eq('id', jobId)
        .maybeSingle();

    // Soft delete: mark status as 'archived' (matches the DB status enum).
    await _client
        .from('job_listings')
        .update({'status': 'archived'})
        .eq('id', jobId);

    await logAdminAction(
      AdminActionLog(
        id: _pendingId,
        adminUserId: _adminUserId,
        actionType: AdminActionLog.actionDelete,
        resourceType: AdminActionLog.resourceJobListing,
        resourceId: jobId,
        changesBefore: beforeRow != null
            ? Map<String, dynamic>.from(beforeRow)
            : null,
        reason: reason,
        timestamp: DateTime.now(),
      ),
    );
  }

  // ── Analytics ─────────────────────────────────────────────────────────────

  @override
  Future<int> getApplicationCountForJob(String jobId) async {
    final rows = await _client
        .from('job_applications')
        .select('id')
        .eq('job_listing_id', jobId);
    return rows.length;
  }

  @override
  Future<int> getTotalJobSeekerCount() async {
    final rows = await _client.from('job_seeker_profiles').select('user_id');
    return rows.length;
  }

  @override
  Future<int> getTotalEmployerCount() async {
    final rows = await _client.from('employer_profiles').select('id');
    return rows.length;
  }

  Application _fromApplicationRow(Map<String, dynamic> row) {
    final data = Map<String, dynamic>.from((row['data'] as Map?) ?? const {});
    data['id'] = row['id'] ?? data['id'];
    data['job_listing_id'] = row['job_listing_id'] ?? data['job_listing_id'];
    data['employer_id'] = row['employer_id'] ?? data['employer_id'];
    data['status'] = row['status'] ?? data['status'];
    data['matchPercentage'] =
        row['match_percentage'] ?? data['matchPercentage'];
    data['updated_at'] = row['updated_at'] ?? data['updated_at'];
    data['applied_at'] = row['created_at'] ?? data['applied_at'];
    return Application.fromJson(data);
  }

  Map<String, dynamic> _fromJobListingRow(Map<String, dynamic> row) {
    return {
      'id': row['id'],
      'employerId': row['employer_id'],
      'title': row['title'],
      'company': row['company'],
      'location': row['location'],
      'type': row['employment_type'],
      'crewRole': row['crew_role'],
      'crewPosition': row['crew_position'],
      'faaRules': List<String>.from((row['faa_rules'] as List?) ?? const []),
      'description': row['description'],
      'faaCertificates': List<String>.from(
        (row['faa_certificates'] as List?) ?? const [],
      ),
      'typeRatingsRequired': List<String>.from(
        (row['type_ratings_required'] as List?) ?? const [],
      ),
      'flightExperience': List<String>.from(
        (row['flight_experience'] as List?) ?? const [],
      ),
      'flightHours': Map<String, dynamic>.from(
        (row['flight_hours'] as Map?) ?? const {},
      ),
      'preferredFlightHours': List<String>.from(
        (row['preferred_flight_hours'] as List?) ?? const [],
      ),
      'instructorHours': Map<String, dynamic>.from(
        (row['instructor_hours'] as Map?) ?? const {},
      ),
      'preferredInstructorHours': List<String>.from(
        (row['preferred_instructor_hours'] as List?) ?? const [],
      ),
      'specialtyExperience': List<String>.from(
        (row['specialty_experience'] as List?) ?? const [],
      ),
      'specialtyHours': Map<String, dynamic>.from(
        (row['specialty_hours'] as Map?) ?? const {},
      ),
      'preferredSpecialtyHours': List<String>.from(
        (row['preferred_specialty_hours'] as List?) ?? const [],
      ),
      'aircraftFlown': List<String>.from(
        (row['aircraft_flown'] as List?) ?? const [],
      ),
      'salaryRange': row['salary_range'],
      'minimumHours': row['minimum_hours'],
      'benefits': List<String>.from((row['benefits'] as List?) ?? const []),
      'deadlineDate': row['deadline_date'],
      'createdAt': row['created_at'],
      'updatedAt': row['updated_at'],
      'autoRejectThreshold':
          (row['auto_reject_threshold'] as num?)?.toInt() ?? 0,
      'reapplyWindowDays': (row['reapply_window_days'] as num?)?.toInt() ?? 30,
      'isActive': row['status'] == 'active',
      'archivedAt': row['status'] == 'archived' ? row['updated_at'] : null,
    };
  }

  Map<String, dynamic> _fromJobSeekerRow(Map<String, dynamic> row) {
    return {
      'fullName': row['full_name'],
      'email': row['email'],
      'phone': row['phone'],
      'city': row['city'],
      'stateOrProvince': row['state_or_province'],
      'country': row['country'],
      'faaCertificates': List<String>.from(
        (row['faa_certificates'] as List?) ?? const [],
      ),
      'typeRatings': List<String>.from(
        (row['type_ratings'] as List?) ?? const [],
      ),
      'flightHours': Map<String, dynamic>.from(
        (row['flight_hours'] as Map?) ?? const {},
      ),
      'flightHoursTypes': List<String>.from(
        (row['flight_hours_types'] as List?) ?? const [],
      ),
      'specialtyFlightHours': List<String>.from(
        (row['specialty_flight_hours'] as List?) ?? const [],
      ),
      'specialtyFlightHoursMap': Map<String, dynamic>.from(
        (row['specialty_flight_hours_map'] as Map?) ?? const {},
      ),
      'aircraftFlown': List<String>.from(
        (row['aircraft_flown'] as List?) ?? const [],
      ),
      'totalFlightHours': row['total_flight_hours'] ?? 0,
    };
  }

  Map<String, dynamic> _fromEmployerRow(Map<String, dynamic> row) {
    return {
      'id': row['id'],
      'companyName': row['company_name'],
      'headquartersAddressLine1': row['headquarters_address_line1'],
      'headquartersAddressLine2': row['headquarters_address_line2'],
      'headquartersCity': row['headquarters_city'],
      'headquartersState': row['headquarters_state'],
      'headquartersPostalCode': row['headquarters_postal_code'],
      'headquartersCountry': row['headquarters_country'],
      'companyBannerUrl': row['company_banner_url'],
      'companyLogoUrl': row['company_logo_url'],
      'website': row['website'],
      'contactName': row['contact_name'],
      'contactEmail': row['contact_email'],
      'contactPhone': row['contact_phone'],
      'companyDescription': row['company_description'],
      'companyBenefits': List<String>.from(
        (row['company_benefits'] as List?) ?? const [],
      ),
    };
  }
}
