import 'package:supabase_flutter/supabase_flutter.dart';

import '../models/admin_action_log.dart';
import '../models/application.dart';
import '../models/employer_moderation.dart';
import '../models/employer_profile.dart';
import '../models/job_listing.dart';
import '../models/job_listing_report.dart';
import '../models/job_seeker_moderation.dart';
import '../models/job_seeker_profile.dart';
import '../repositories/admin_repository.dart';

class SupabaseAdminRepository implements AdminRepository {
  const SupabaseAdminRepository(this._client, this._adminUserId);

  final SupabaseClient _client;
  final String _adminUserId;

  /// Placeholder id for [AdminActionLog] instances that will be persisted via
  /// [logAdminAction].  The real id is generated by the database
  /// (`gen_random_uuid()` default) — [logAdminAction] strips this field before
  /// inserting, so the value here is never written to the database.
  static const _pendingId = '';

  // ── Action Logging ────────────────────────────────────────────────────────

  @override
  Future<void> logAdminAction(AdminActionLog log) async {
    // Omit 'id' so the database generates it via gen_random_uuid() default.
    final payload = Map<String, dynamic>.from(log.toJson())..remove('id');
    await _client.from('admin_action_logs').insert(payload);
  }

  @override
  Future<List<AdminActionLog>> getAdminActionLogs({
    DateTime? startDate,
    DateTime? endDate,
    String? actionType,
    String? resourceType,
  }) async {
    var query = _client.from('admin_action_logs').select();

    if (startDate != null) {
      query = query.gte('timestamp', startDate.toIso8601String());
    }
    if (endDate != null) {
      query = query.lte('timestamp', endDate.toIso8601String());
    }
    if (actionType != null && actionType.isNotEmpty) {
      query = query.eq('action_type', actionType);
    }
    if (resourceType != null && resourceType.isNotEmpty) {
      query = query.eq('resource_type', resourceType);
    }

    final rows = await query.order('timestamp', ascending: false);
    return rows
        .map((r) => AdminActionLog.fromJson(Map<String, dynamic>.from(r)))
        .toList();
  }

  // ── Read Data ─────────────────────────────────────────────────────────────

  @override
  Future<JobSeekerProfile?> getJobSeekerProfile(String userId) async {
    final row = await _client
        .from('job_seeker_profiles')
        .select()
        .eq('user_id', userId)
        .maybeSingle();
    if (row == null) {
      return null;
    }
    return JobSeekerProfile.fromJson(_fromJobSeekerRow(row));
  }

  @override
  Future<EmployerProfile?> getEmployerProfile(String employerId) async {
    final row = await _client
        .from('employer_profiles')
        .select()
        .eq('id', employerId)
        .maybeSingle();
    if (row == null) {
      return null;
    }
    return EmployerProfile.fromJson(_fromEmployerRow(row));
  }

  @override
  Future<List<Application>> getApplicationsForJob(String jobId) async {
    final rows = await _client
        .from('job_applications')
        .select()
        .eq('job_listing_id', jobId)
        .order('updated_at', ascending: false);
    return rows
        .map((r) => _fromApplicationRow(Map<String, dynamic>.from(r)))
        .toList();
  }

  @override
  Future<List<JobListing>> getAllJobListings() async {
    final rows = await _client
        .from('job_listings')
        .select()
        .order('created_at', ascending: false);
    return rows.map((r) => JobListing.fromJson(_fromJobListingRow(r))).toList();
  }

  @override
  Future<List<Application>> getAllApplications() async {
    final rows = await _client
        .from('job_applications')
        .select()
        .order('updated_at', ascending: false);
    return rows
        .map((r) => _fromApplicationRow(Map<String, dynamic>.from(r)))
        .toList();
  }

  @override
  Future<List<JobListingReport>> getJobListingReports({String? status}) async {
    var query = _client.from('job_listing_reports').select();
    if (status != null && status.isNotEmpty) {
      query = query.eq('status', status);
    }
    final rows = await query.order('created_at', ascending: false);
    return rows
        .map((row) => JobListingReport.fromJson(Map<String, dynamic>.from(row)))
        .toList();
  }

  @override
  Future<List<EmployerModeration>> getEmployerModerationSummaries() async {
    final profileRows = await _client
        .from('employer_profiles')
        .select('id, company_name');
    final moderationRows = await _client.from('employer_moderation').select();
    final moderationById = {
      for (final row in moderationRows)
        row['employer_id']?.toString() ?? '': Map<String, dynamic>.from(row),
    };

    return profileRows.map((row) {
      final profile = Map<String, dynamic>.from(row);
      final moderation =
          moderationById[profile['id']?.toString() ?? ''] ?? const {};
      return EmployerModeration.fromJson({
        'employer_id': profile['id'],
        'company_name': profile['company_name'],
        ...moderation,
      });
    }).toList();
  }

  @override
  Future<List<JobSeekerModeration>> getJobSeekerModerationSummaries() async {
    final profileRows = await _client
        .from('job_seeker_profiles')
        .select('user_id, full_name, email');
    final moderationRows = await _client.from('job_seeker_moderation').select();
    final moderationById = {
      for (final row in moderationRows)
        row['user_id']?.toString() ?? '': Map<String, dynamic>.from(row),
    };

    return profileRows.map((row) {
      final profile = Map<String, dynamic>.from(row);
      final moderation =
          moderationById[profile['user_id']?.toString() ?? ''] ?? const {};
      return JobSeekerModeration.fromJson({
        'user_id': profile['user_id'],
        'display_name': profile['full_name'],
        'email': profile['email'],
        ...moderation,
      });
    }).toList();
  }

  // ── Edit Data ─────────────────────────────────────────────────────────────

  @override
  Future<void> updateJobListing(
    String jobId,
    JobListing updated,
    String reason,
  ) async {
    final beforeRow = await _client
        .from('job_listings')
        .select()
        .eq('id', jobId)
        .maybeSingle();

    await _client.from('job_listings').update(updated.toJson()).eq('id', jobId);

    await logAdminAction(
      AdminActionLog(
        id: _pendingId,
        adminUserId: _adminUserId,
        actionType: AdminActionLog.actionUpdate,
        resourceType: AdminActionLog.resourceJobListing,
        resourceId: jobId,
        changesBefore: beforeRow != null
            ? Map<String, dynamic>.from(beforeRow)
            : null,
        changesAfter: updated.toJson(),
        reason: reason,
        timestamp: DateTime.now(),
      ),
    );
  }

  @override
  Future<void> updateApplication(
    String appId,
    Application updated,
    String reason,
  ) async {
    final beforeRow = await _client
        .from('job_applications')
        .select()
        .eq('id', appId)
        .maybeSingle();

    await _client
        .from('job_applications')
        .update(updated.toJson())
        .eq('id', appId);

    await logAdminAction(
      AdminActionLog(
        id: _pendingId,
        adminUserId: _adminUserId,
        actionType: AdminActionLog.actionUpdate,
        resourceType: AdminActionLog.resourceApplication,
        resourceId: appId,
        changesBefore: beforeRow != null
            ? Map<String, dynamic>.from(beforeRow)
            : null,
        changesAfter: updated.toJson(),
        reason: reason,
        timestamp: DateTime.now(),
      ),
    );
  }

  @override
  Future<void> updateJobSeekerProfile(
    String userId,
    JobSeekerProfile updated,
    String reason,
  ) async {
    final beforeRow = await _client
        .from('job_seeker_profiles')
        .select()
        .eq('user_id', userId)
        .maybeSingle();

    await _client
        .from('job_seeker_profiles')
        .update(updated.toJson())
        .eq('user_id', userId);

    await logAdminAction(
      AdminActionLog(
        id: _pendingId,
        adminUserId: _adminUserId,
        actionType: AdminActionLog.actionUpdate,
        resourceType: AdminActionLog.resourceJobSeekerProfile,
        resourceId: userId,
        changesBefore: beforeRow != null
            ? Map<String, dynamic>.from(beforeRow)
            : null,
        changesAfter: updated.toJson(),
        reason: reason,
        timestamp: DateTime.now(),
      ),
    );
  }

  @override
  Future<void> updateEmployerProfile(
    String empId,
    EmployerProfile updated,
    String reason,
  ) async {
    final beforeRow = await _client
        .from('employer_profiles')
        .select()
        .eq('id', empId)
        .maybeSingle();

    await _client
        .from('employer_profiles')
        .update(updated.toJson())
        .eq('id', empId);

    await logAdminAction(
      AdminActionLog(
        id: _pendingId,
        adminUserId: _adminUserId,
        actionType: AdminActionLog.actionUpdate,
        resourceType: AdminActionLog.resourceEmployerProfile,
        resourceId: empId,
        changesBefore: beforeRow != null
            ? Map<String, dynamic>.from(beforeRow)
            : null,
        changesAfter: updated.toJson(),
        reason: reason,
        timestamp: DateTime.now(),
      ),
    );
  }

  // ── Delete ────────────────────────────────────────────────────────────────

  @override
  Future<void> deleteApplication(String appId, String reason) async {
    final beforeRow = await _client
        .from('job_applications')
        .select()
        .eq('id', appId)
        .maybeSingle();

    final currentData = Map<String, dynamic>.from(
      (beforeRow?['data'] as Map?) ?? const {},
    );
    currentData['is_archived'] = true;
    currentData['updated_at'] = DateTime.now().toIso8601String();

    await _client
        .from('job_applications')
        .update({
          'data': currentData,
          'updated_at': DateTime.now().toIso8601String(),
        })
        .eq('id', appId);

    final seekerId = beforeRow?['applicant_user_id']?.toString();
    if (seekerId != null && seekerId.isNotEmpty) {
      await _incrementJobSeekerDeletedApplicationCount(
        userId: seekerId,
        displayName: currentData['applicant_name']?.toString() ?? '',
        email: currentData['applicant_email']?.toString() ?? '',
      );
    }

    await logAdminAction(
      AdminActionLog(
        id: _pendingId,
        adminUserId: _adminUserId,
        actionType: AdminActionLog.actionDelete,
        resourceType: AdminActionLog.resourceApplication,
        resourceId: appId,
        changesBefore: beforeRow != null
            ? Map<String, dynamic>.from(beforeRow)
            : null,
        reason: reason,
        timestamp: DateTime.now(),
      ),
    );
  }

  @override
  Future<void> deleteJobListing(String jobId, String reason) async {
    final beforeRow = await _client
        .from('job_listings')
        .select()
        .eq('id', jobId)
        .maybeSingle();

    // Soft delete: mark status as 'archived' (matches the DB status enum).
    await _client
        .from('job_listings')
        .update({'status': 'archived'})
        .eq('id', jobId);

    final employerId = beforeRow?['employer_id']?.toString();
    if (employerId != null && employerId.isNotEmpty) {
      await _incrementEmployerDeletedJobCount(
        employerId: employerId,
        companyName: beforeRow?['company']?.toString() ?? '',
      );
    }

    await _client
        .from('job_listing_reports')
        .update({
          'status': JobListingReport.statusDeleted,
          'reviewed_at': DateTime.now().toIso8601String(),
          'reviewed_by_admin_user_id': _adminUserId,
          'admin_notes': reason,
        })
        .eq('job_listing_id', jobId)
        .eq('status', JobListingReport.statusOpen);

    await logAdminAction(
      AdminActionLog(
        id: _pendingId,
        adminUserId: _adminUserId,
        actionType: AdminActionLog.actionDelete,
        resourceType: AdminActionLog.resourceJobListing,
        resourceId: jobId,
        changesBefore: beforeRow != null
            ? Map<String, dynamic>.from(beforeRow)
            : null,
        reason: reason,
        timestamp: DateTime.now(),
      ),
    );
  }

  @override
  Future<void> deleteEmployerProfile(String employerId, String reason) async {
    final isAdminOwnedEmployer = await _isAdminOwnedEmployer(employerId);
    if (isAdminOwnedEmployer) {
      throw StateError('Cannot delete an admin employer profile.');
    }

    final beforeRow = await _client
        .from('employer_profiles')
        .select()
        .eq('id', employerId)
        .maybeSingle();

    final listingRows = await _client
        .from('job_listings')
        .select('id')
        .eq('employer_id', employerId);
    final listingIds = listingRows
        .map((row) => row['id']?.toString() ?? '')
        .where((id) => id.isNotEmpty)
        .toList();

    // Hard-delete all listings owned by this employer before deleting profile.
    await _client.from('job_listings').delete().eq('employer_id', employerId);

    for (final listingId in listingIds) {
      await _client
          .from('job_listing_reports')
          .update({
            'status': JobListingReport.statusDeleted,
            'reviewed_at': DateTime.now().toIso8601String(),
            'reviewed_by_admin_user_id': _adminUserId,
            'admin_notes':
                'Listing deleted due to employer profile deletion: $reason',
          })
          .eq('job_listing_id', listingId)
          .eq('status', JobListingReport.statusOpen);
    }

    await _client.from('employer_profiles').delete().eq('id', employerId);

    await logAdminAction(
      AdminActionLog(
        id: _pendingId,
        adminUserId: _adminUserId,
        actionType: AdminActionLog.actionDelete,
        resourceType: AdminActionLog.resourceEmployerProfile,
        resourceId: employerId,
        changesBefore: beforeRow != null
            ? Map<String, dynamic>.from(beforeRow)
            : null,
        changesAfter: {'deleted_job_listing_count': listingIds.length},
        reason: reason,
        timestamp: DateTime.now(),
      ),
    );
  }

  @override
  Future<void> deleteJobSeekerProfile(String userId, String reason) async {
    final isAdminUser = await _isAdminUser(userId);
    if (isAdminUser) {
      throw StateError('Cannot delete an admin job seeker profile.');
    }

    final beforeRow = await _client
        .from('job_seeker_profiles')
        .select()
        .eq('user_id', userId)
        .maybeSingle();

    await _client.from('job_seeker_profiles').delete().eq('user_id', userId);

    await logAdminAction(
      AdminActionLog(
        id: _pendingId,
        adminUserId: _adminUserId,
        actionType: AdminActionLog.actionDelete,
        resourceType: AdminActionLog.resourceJobSeekerProfile,
        resourceId: userId,
        changesBefore: beforeRow != null
            ? Map<String, dynamic>.from(beforeRow)
            : null,
        reason: reason,
        timestamp: DateTime.now(),
      ),
    );
  }

  // ── Analytics ─────────────────────────────────────────────────────────────

  @override
  Future<int> getApplicationCountForJob(String jobId) async {
    final rows = await _client
        .from('job_applications')
        .select('id')
        .eq('job_listing_id', jobId);
    return rows.length;
  }

  @override
  Future<int> getTotalJobSeekerCount() async {
    final rows = await _client.from('job_seeker_profiles').select('user_id');
    return rows.length;
  }

  @override
  Future<int> getTotalEmployerCount() async {
    final rows = await _client.from('employer_profiles').select('id');
    return rows.length;
  }

  @override
  Future<void> resolveJobListingReport(
    String reportId, {
    required String status,
    String? adminNotes,
  }) async {
    await _client
        .from('job_listing_reports')
        .update({
          'status': status,
          'admin_notes': adminNotes,
          'reviewed_at': DateTime.now().toIso8601String(),
          'reviewed_by_admin_user_id': _adminUserId,
        })
        .eq('id', reportId);
  }

  @override
  Future<void> setEmployerBan(
    String employerId, {
    required bool isBanned,
    String? reason,
    String? companyName,
  }) async {
    var deletedJobListingCount = 0;
    var deletedApplicationCount = 0;

    if (isBanned) {
      final isAdminOwnedEmployer = await _isAdminOwnedEmployer(employerId);
      if (isAdminOwnedEmployer) {
        throw StateError('Cannot ban an admin employer profile.');
      }

      final listingRows = await _client
          .from('job_listings')
          .select('id')
          .eq('employer_id', employerId);
      final listingIds = listingRows
          .map((row) => row['id']?.toString() ?? '')
          .where((id) => id.isNotEmpty)
          .toList();
      deletedJobListingCount = listingIds.length;

      final applicationRows = await _client
          .from('job_applications')
          .select('id')
          .eq('employer_id', employerId);
      deletedApplicationCount = applicationRows.length;

      // Deleting listings will cascade to related applications.
      await _client.from('job_listings').delete().eq('employer_id', employerId);

      for (final listingId in listingIds) {
        await _client
            .from('job_listing_reports')
            .update({
              'status': JobListingReport.statusDeleted,
              'reviewed_at': DateTime.now().toIso8601String(),
              'reviewed_by_admin_user_id': _adminUserId,
              'admin_notes':
                  'Listing deleted due to employer ban: ${reason ?? ''}',
            })
            .eq('job_listing_id', listingId)
            .eq('status', JobListingReport.statusOpen);
      }
    }

    final beforeRow = await _client
        .from('employer_moderation')
        .select()
        .eq('employer_id', employerId)
        .maybeSingle();

    final previousDeletedJobCount =
        ((beforeRow?['admin_deleted_job_count'] as num?)?.toInt() ?? 0);

    final nextRow = {
      'employer_id': employerId,
      if (companyName != null) 'company_name': companyName,
      'admin_deleted_job_count':
          previousDeletedJobCount + deletedJobListingCount,
      'is_banned': isBanned,
      'banned_at': isBanned ? DateTime.now().toIso8601String() : null,
      'ban_reason': isBanned ? (reason ?? '') : '',
    };

    await _client.from('employer_moderation').upsert(nextRow);

    await logAdminAction(
      AdminActionLog(
        id: _pendingId,
        adminUserId: _adminUserId,
        actionType: AdminActionLog.actionUpdate,
        resourceType: AdminActionLog.resourceEmployerProfile,
        resourceId: employerId,
        changesBefore: beforeRow == null
            ? null
            : Map<String, dynamic>.from(beforeRow),
        changesAfter: nextRow,
        reason: isBanned
            ? 'Employer banned${(reason ?? '').trim().isEmpty ? '' : ': $reason'}'
            : 'Employer unbanned',
        timestamp: DateTime.now(),
      ),
    );
  }

  @override
  Future<void> setJobSeekerBan(
    String userId, {
    required bool isBanned,
    String? reason,
    String? displayName,
    String? email,
  }) async {
    var deletedApplicationCount = 0;

    if (isBanned) {
      final isAdminUser = await _isAdminUser(userId);
      if (isAdminUser) {
        throw StateError('Cannot ban an admin job seeker profile.');
      }

      final applicationRows = await _client
          .from('job_applications')
          .select('id')
          .eq('applicant_user_id', userId);
      deletedApplicationCount = applicationRows.length;

      await _client
          .from('job_applications')
          .delete()
          .eq('applicant_user_id', userId);
    }

    final beforeRow = await _client
        .from('job_seeker_moderation')
        .select()
        .eq('user_id', userId)
        .maybeSingle();

    final previousDeletedApplicationCount =
        ((beforeRow?['admin_deleted_application_count'] as num?)?.toInt() ?? 0);

    final nextRow = {
      'user_id': userId,
      if (displayName != null) 'display_name': displayName,
      if (email != null) 'email': email,
      'admin_deleted_application_count':
          previousDeletedApplicationCount + deletedApplicationCount,
      'is_banned': isBanned,
      'banned_at': isBanned ? DateTime.now().toIso8601String() : null,
      'ban_reason': isBanned ? (reason ?? '') : '',
    };

    await _client.from('job_seeker_moderation').upsert(nextRow);

    await logAdminAction(
      AdminActionLog(
        id: _pendingId,
        adminUserId: _adminUserId,
        actionType: AdminActionLog.actionUpdate,
        resourceType: AdminActionLog.resourceJobSeekerProfile,
        resourceId: userId,
        changesBefore: beforeRow == null
            ? null
            : Map<String, dynamic>.from(beforeRow),
        changesAfter: nextRow,
        reason: isBanned
            ? 'Job seeker banned${(reason ?? '').trim().isEmpty ? '' : ': $reason'}'
            : 'Job seeker unbanned',
        timestamp: DateTime.now(),
      ),
    );
  }

  Application _fromApplicationRow(Map<String, dynamic> row) {
    final data = Map<String, dynamic>.from((row['data'] as Map?) ?? const {});
    data['id'] = row['id'] ?? data['id'];
    data['job_listing_id'] = row['job_listing_id'] ?? data['job_listing_id'];
    data['employer_id'] = row['employer_id'] ?? data['employer_id'];
    data['status'] = row['status'] ?? data['status'];
    data['matchPercentage'] =
        row['match_percentage'] ?? data['matchPercentage'];
    data['updated_at'] = row['updated_at'] ?? data['updated_at'];
    data['applied_at'] = row['created_at'] ?? data['applied_at'];
    return Application.fromJson(data);
  }

  Map<String, dynamic> _fromJobListingRow(Map<String, dynamic> row) {
    return {
      'id': row['id'],
      'employerId': row['employer_id'],
      'title': row['title'],
      'company': row['company'],
      'location': row['location'],
      'type': row['employment_type'],
      'crewRole': row['crew_role'],
      'crewPosition': row['crew_position'],
      'faaRules': List<String>.from((row['faa_rules'] as List?) ?? const []),
      'description': row['description'],
      'faaCertificates': List<String>.from(
        (row['faa_certificates'] as List?) ?? const [],
      ),
      'typeRatingsRequired': List<String>.from(
        (row['type_ratings_required'] as List?) ?? const [],
      ),
      'flightExperience': List<String>.from(
        (row['flight_experience'] as List?) ?? const [],
      ),
      'flightHours': Map<String, dynamic>.from(
        (row['flight_hours'] as Map?) ?? const {},
      ),
      'preferredFlightHours': List<String>.from(
        (row['preferred_flight_hours'] as List?) ?? const [],
      ),
      'instructorHours': Map<String, dynamic>.from(
        (row['instructor_hours'] as Map?) ?? const {},
      ),
      'preferredInstructorHours': List<String>.from(
        (row['preferred_instructor_hours'] as List?) ?? const [],
      ),
      'specialtyExperience': List<String>.from(
        (row['specialty_experience'] as List?) ?? const [],
      ),
      'specialtyHours': Map<String, dynamic>.from(
        (row['specialty_hours'] as Map?) ?? const {},
      ),
      'preferredSpecialtyHours': List<String>.from(
        (row['preferred_specialty_hours'] as List?) ?? const [],
      ),
      'aircraftFlown': List<String>.from(
        (row['aircraft_flown'] as List?) ?? const [],
      ),
      'salaryRange': row['salary_range'],
      'minimumHours': row['minimum_hours'],
      'benefits': List<String>.from((row['benefits'] as List?) ?? const []),
      'deadlineDate': row['deadline_date'],
      'createdAt': row['created_at'],
      'updatedAt': row['updated_at'],
      'autoRejectThreshold':
          (row['auto_reject_threshold'] as num?)?.toInt() ?? 0,
      'reapplyWindowDays': (row['reapply_window_days'] as num?)?.toInt() ?? 30,
      'isActive': row['status'] == 'active',
      'archivedAt': row['status'] == 'archived' ? row['updated_at'] : null,
    };
  }

  Map<String, dynamic> _fromJobSeekerRow(Map<String, dynamic> row) {
    return {
      'fullName': row['full_name'],
      'email': row['email'],
      'phone': row['phone'],
      'city': row['city'],
      'stateOrProvince': row['state_or_province'],
      'country': row['country'],
      'faaCertificates': List<String>.from(
        (row['faa_certificates'] as List?) ?? const [],
      ),
      'typeRatings': List<String>.from(
        (row['type_ratings'] as List?) ?? const [],
      ),
      'flightHours': Map<String, dynamic>.from(
        (row['flight_hours'] as Map?) ?? const {},
      ),
      'flightHoursTypes': List<String>.from(
        (row['flight_hours_types'] as List?) ?? const [],
      ),
      'specialtyFlightHours': List<String>.from(
        (row['specialty_flight_hours'] as List?) ?? const [],
      ),
      'specialtyFlightHoursMap': Map<String, dynamic>.from(
        (row['specialty_flight_hours_map'] as Map?) ?? const {},
      ),
      'aircraftFlown': List<String>.from(
        (row['aircraft_flown'] as List?) ?? const [],
      ),
      'totalFlightHours': row['total_flight_hours'] ?? 0,
    };
  }

  Map<String, dynamic> _fromEmployerRow(Map<String, dynamic> row) {
    return {
      'id': row['id'],
      'companyName': row['company_name'],
      'headquartersAddressLine1': row['headquarters_address_line1'],
      'headquartersAddressLine2': row['headquarters_address_line2'],
      'headquartersCity': row['headquarters_city'],
      'headquartersState': row['headquarters_state'],
      'headquartersPostalCode': row['headquarters_postal_code'],
      'headquartersCountry': row['headquarters_country'],
      'companyBannerUrl': row['company_banner_url'],
      'companyLogoUrl': row['company_logo_url'],
      'website': row['website'],
      'contactName': row['contact_name'],
      'contactEmail': row['contact_email'],
      'contactPhone': row['contact_phone'],
      'companyDescription': row['company_description'],
      'companyBenefits': List<String>.from(
        (row['company_benefits'] as List?) ?? const [],
      ),
    };
  }

  Future<void> _incrementEmployerDeletedJobCount({
    required String employerId,
    required String companyName,
  }) async {
    final existing = await _client
        .from('employer_moderation')
        .select()
        .eq('employer_id', employerId)
        .maybeSingle();
    final count =
        ((existing?['admin_deleted_job_count'] as num?)?.toInt() ?? 0) + 1;
    await _client.from('employer_moderation').upsert({
      'employer_id': employerId,
      'company_name': companyName,
      'admin_deleted_job_count': count,
      'is_banned': existing?['is_banned'] ?? false,
      'ban_reason': existing?['ban_reason'] ?? '',
      'banned_at': existing?['banned_at'],
    });
  }

  Future<void> _incrementJobSeekerDeletedApplicationCount({
    required String userId,
    required String displayName,
    required String email,
  }) async {
    final existing = await _client
        .from('job_seeker_moderation')
        .select()
        .eq('user_id', userId)
        .maybeSingle();
    final count =
        ((existing?['admin_deleted_application_count'] as num?)?.toInt() ?? 0) +
        1;
    await _client.from('job_seeker_moderation').upsert({
      'user_id': userId,
      'display_name': displayName,
      'email': email,
      'admin_deleted_application_count': count,
      'is_banned': existing?['is_banned'] ?? false,
      'ban_reason': existing?['ban_reason'] ?? '',
      'banned_at': existing?['banned_at'],
    });
  }

  Future<bool> _isAdminUser(String userId) async {
    final result = await _client.rpc(
      'user_is_admin',
      params: {'target_user_id': userId},
    );
    return result == true;
  }

  Future<bool> _isAdminOwnedEmployer(String employerId) async {
    final result = await _client.rpc(
      'employer_owner_is_admin',
      params: {'target_employer_id': employerId},
    );
    return result == true;
  }
}
