class ApplicationFeedback {
  final String id;
  final String applicationId;
  final String message;
  final String feedbackType; // 'interested', 'future_consideration', 'not_fit', 'custom'
  final bool sentByEmployer;
  final DateTime sentAt;
  final bool isAutoGenerated; // true when created by the system (e.g. auto-reject)

  static const String feedbackTypeInterested = 'interested';
  static const String feedbackTypeFutureConsideration = 'future_consideration';
  static const String feedbackTypeNotFit = 'not_fit';
  static const String feedbackTypeCustom = 'custom';

  const ApplicationFeedback({
    required this.id,
    required this.applicationId,
    required this.message,
    required this.feedbackType,
    required this.sentByEmployer,
    required this.sentAt,
    this.isAutoGenerated = false,
  });

  factory ApplicationFeedback.fromJson(Map<String, dynamic> json) {
    DateTime parseSentAt() {
      final raw = json['sent_at'] ?? json['sentAt'];
      if (raw != null) {
        return DateTime.tryParse(raw.toString()) ?? DateTime.now();
      }
      return DateTime.now();
    }

    return ApplicationFeedback(
      id: json['id']?.toString() ?? '',
      applicationId:
          json['application_id']?.toString() ??
          json['applicationId']?.toString() ??
          '',
      message: json['message']?.toString() ?? '',
      feedbackType:
          json['feedback_type']?.toString() ??
          json['feedbackType']?.toString() ??
          feedbackTypeCustom,
      sentByEmployer:
          (json['sent_by_employer'] as bool?) ??
          (json['sentByEmployer'] as bool?) ??
          true,
      sentAt: parseSentAt(),
      isAutoGenerated:
          (json['is_auto_generated'] as bool?) ??
          (json['isAutoGenerated'] as bool?) ??
          false,
    );
  }

  Map<String, dynamic> toJson() => {
    'id': id,
    'application_id': applicationId,
    'message': message,
    'feedback_type': feedbackType,
    'sent_by_employer': sentByEmployer,
    'sent_at': sentAt.toIso8601String(),
    'is_auto_generated': isAutoGenerated,
  };

  ApplicationFeedback copyWith({
    String? message,
    String? feedbackType,
    bool? sentByEmployer,
    DateTime? sentAt,
    bool? isAutoGenerated,
  }) {
    return ApplicationFeedback(
      id: id,
      applicationId: applicationId,
      message: message ?? this.message,
      feedbackType: feedbackType ?? this.feedbackType,
      sentByEmployer: sentByEmployer ?? this.sentByEmployer,
      sentAt: sentAt ?? this.sentAt,
      isAutoGenerated: isAutoGenerated ?? this.isAutoGenerated,
    );
  }
}
